/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import GoogleMap.Mapa;
import Utilities.JsonFileOpenerConexiones;
import Utilities.JsonFileOpenerLocalidadesConductores;
import Utilities.JsonFileOpenerLocalidadesUsuarios;
import Utilities.JsonFileOpenerLugares;
import Utilities.JsonFileOpenerUsuarios;
import com.teamdev.jxmaps.LatLng;
import com.teamdev.jxmaps.MapViewOptions;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Oscar
 */
public class UbicacionesMapa extends javax.swing.JPanel {

    /**
     * Creates new form UbicacionesMapa
     */
    public UbicacionesMapa() {
        initComponents();
        
    }
    
    public void cargarUbicaciones(String rutaArchivoLugares, String rutaArchivoConexiones){
        
        String apiKey = "AIzaSyAQIa8L5-4XCFJbFkKwlHoPu-7psnrEdJo";
        String apiKeyPrestada = "AIzaSyAR-xSrf5bYghVZDdfQ1F0Yk3nWpyViyig";

        JsonFileOpenerLugares nuevoLugares = new JsonFileOpenerLugares();
        JsonFileOpenerConexiones nuevoConexiones = new JsonFileOpenerConexiones();
        
        nuevoLugares.abrir(rutaArchivoLugares);
        nuevoConexiones.abrir(rutaArchivoConexiones);
        
        MapViewOptions opciones = new MapViewOptions();
        opciones.importPlaces();
        opciones.setApiKey(apiKey);

        Mapa mapa = new Mapa(opciones);
        mapa.esperar();
        
        for(int i = 0; i<nuevoLugares.getSize(); i++){
            
            double lat1 = nuevoLugares.lugarGetLatitud(i);
            double long1 = nuevoLugares.lugarGetLongitud(i);
        
            double lat2 = nuevoLugares.lugarGetLatitud(1);
            double long2 = nuevoLugares.lugarGetLongitud(1);
        
            LatLng latlong1 = new LatLng(lat1, long1);
            //LatLng latlong2 = new LatLng(lat2, long2);
            
            //mapa.agregarLinea(latlong1, latlong2, true);
            mapa.centrarEnUsuario(latlong1);
            mapa.agregarMarcador(latlong1);
        }
        
        for(int i = 0; i<nuevoConexiones.getNoItems(); i++){
            //Agregar Lineas cuando ya tengamos Tabla Hash
        }
        

        mapa.setVisible(true);

        JFrame frame = new JFrame("Mapa");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setSize(1000, 800);
        frame.add(mapa, BorderLayout.CENTER);
        frame.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
